# Macro file for run 3 rpd training simulation

# Initialize kernel
/run/initialize


/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/run/particle/verbose 0


#################################
# gps Options
#################################

#/gps/particle ion
#/gps/ion 82 208 0 0.0
#/gps/energy 31.2 TeV

# using alphas is useful if you would like to visualize the tracks (Pb ions require much more computing time)
#/gps/particle ion
#/gps/ion 2 4 0 0.0
#/gps/energy 600 GeV

#/gps/particle proton
#/gps/particle neutron
/gps/particle pi0

# the beam energy is in gaussian profile
/gps/ene/type Gauss
/gps/ene/mono 150 GeV
/gps/ene/sigma 1 MeV


# General particle source
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. -150. mm
/gps/pos/radius 1. mm
/gps/pos/sigma_r 2. mm

#
#
# the incident surface is in the x-y plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
#
#
# the beam is travelling along the z-axis
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
# the beam angular dispersion
/gps/ang/sigma_r 0.00 deg
# 1.0milliradians  = 0.057 deg



#################################
# Prebuilt beam Options
# Note: if /beam/type is selected all gps options will be ignored
# Descriptions of commands can be found in the UI command tree
#################################

/beam/type lhc
/beam/pos 0. 0. -140. m
/beam/projectBeam 0 mm
#/beam/nPrimaries 1
#/beam/LHC/horizontalCrossingAngle 0.100 mrad
#/beam/LHC/verticalCrossingAngle 0.100 mrad



#if using these commands in interactive mode to visualize, use this to allow more events to be displayed (do not use in batch mode)
#/vis/ogl/set/displayListLimit 1000000
