# Macro file for JZCaPA beam test 2018
# 
# To be run preferably in batch, without graphics:
# 
#

# Initialize kernel
/run/initialize


/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/run/particle/verbose 1


#/gps/particle ion
#/gps/ion 82 208 0 0.0
#/gps/energy 31.2 TeV

# using alphas is useful if you would like to visualize the tracks (Pb ions require much more computing time)
/gps/particle ion
/gps/ion 2 4 0 0.0
/gps/energy 600 GeV

#/gps/particle proton
#/gps/particle neutron

# the beam energy is in gaussian profile
#/gps/ene/type Gauss
#/gps/ene/mono 16.8 GeV
#/gps/ene/sigma 0.3 MeV


# General particle source  
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. -15999. mm
/gps/pos/radius 1. mm
/gps/pos/sigma_r 2. mm

#
#
# the incident surface is in the x-y plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
#
#
# the beam is travelling along the z-axis with any angular 
#dispersion (angular despersion set to 0.057)
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0 
/gps/ang/type beam1d 
/gps/ang/sigma_r 0.057 deg 
# 1.0milliradians   0.057 deg 
#

#if using these commands in interactive mode to visualize, use this to allow more events to be displayed
/vis/ogl/set/displayListLimit 1000000

##############################################################
##############################################################
# number of events
/run/beamOn 2
##############################################################
##############################################################