# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfWorkers 4

#
/control/verbose 2
/run/verbose 2
# 
# proton 210 MeV to the direction (0.,0.,-1.)
# 1000 events
#
#/testhadr/ionPhysics FTF
/run/initialize
/gun/particle proton
#/gun/particle ion
#/gun/ion Z A charge excitationEnergy
#/gun/ion 82 208 0 0.0
/gun/energy 3.5 TeV
#
/run/beamOn 1
