# Macro file for JZCaPA beam test 2018
#
# To be run preferably in batch, without graphics:

# Initialize kernel
/run/initialize

/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/run/particle/verbose 1

#/gps/particle ion
#/gps/ion 82 208 0 0.0
#/gps/energy 31.2 TeV

#/gps/particle ion
#/gps/ion 2 4 0 0.0
#/gps/energy 600 GeV

#/gps/particle proton
/gps/particle neutron

# the beam energy is in gaussian profile
/gps/ene/type Gauss
/gps/ene/mono 300 GeV
/gps/ene/sigma 1 MeV

# FUNCTIONING CONE
#/gps/ang/type iso
#/gps/pos/centre 0. 0. -15999. mm
#/gps/ang/maxtheta 0.0022918 deg
#/gps/ang/rot1 0 1 0
#/gps/ang/rot2 1 0 0
# angle corresponds to 0.1 GeV kick for 2.5 TeV neut

# FUNCTIONING PLANE
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/centre 0. 0. -15999. mm
#/gps/pos/halfx 20 mm
#/gps/pos/halfy 20 mm
#/gps/ang/rot1 0 1 0
#/gps/ang/rot2 1 0 0
#/gps/ang/type beam1d

# FUNCTIONING BEAM
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 10. mm
/gps/pos/radius 1. mm
/gps/pos/sigma_r 2. mm
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
/gps/ang/sigma_r 0.00 deg


#if using these commands in interactive mode to visualize, use this to allow more events to be displayed (do not use in batch mode)
/vis/ogl/set/displayListLimit 1000000000

##############################################################
##############################################################
# number of events
/run/beamOn 10
##############################################################
##############################################################
